export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILED = "REMOVE_FROM_CART_FAILED";
export const CART_CHECKOUT_SUCCESS = "CART_CHECKOUT_SUCCESS";
export const CART_CHECKOUT_FAILED = "CART_CHECKOUT_FAILED";
